### ISSUE TITLE
the kube_master_url in skydns-rc.yaml doesn't seem to be right.

### ISSUE THREAD

**Issue by lilwulin** [rimusz/coreos-osx-gui-kubernetes-solo#1]
Shouldn't it be `http://172.19.17.99:8080` instead of  `http://172.17.15.101:8080`?

**Comment by rimusz** [comment]
@lilwulin  oh crap, again copy/paste between projects problem.
Will fix it later one, thanks for reporting

**Comment by rimusz** [comment]
@lilwulin new v0.2.1 fixes it

**Comment by lilwulin** [comment]
Thanks! @rimusz
